tokens:
  # this is a Bot token starting with xoxb-
  slack_token: your bot's Slack API token

cafes:
  default:
    company: company
    name: cafe
    utc_offset: 0  # the UTC offset in int for the local time of the café
  # additional cafés, you can add as many as you'd like
  # cafe2:
  #   company: same-company
  #   name: another-cafe
  #   utc_offset: -5

whitelist_channels:
  - Channel
  - IDs
  - Go
  - Here

guy_fieri_images:
  - https://media.comicbook.com/2019/12/guy-fieri-baby-yoda-meme-1198350-1280x0.jpeg
  - http://vignette2.wikia.nocookie.net/universe-of-smash-bros-lawl/images/a/a3/Guy_Fieri.png
  - https://www.borderstan.com/files/2015/10/guyfieri-0179-pkg_resized.jpg
  - http://food.fnr.sndimg.com/content/dam/images/food/editorial/talent/guy-fieri/FN-TalentAvatar-Guy-Fieri-800x800.jpg.rend.hgtvcom.616.616.jpeg
  - https://vignette1.wikia.nocookie.net/playstationallstarsfanfictionroyale/images/7/72/Guy-fieri-.jpg/revision/latest?cb=20150618032144
  - http://static4.businessinsider.com/image/4fb12ce269bedd0305000002/look-at-what-happens-when-food-network-host-guy-fieri-eats-at-a-restaurant-for-his-show.jpg
  - https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FDZP3qbGVwAElaw_.jpg

guy_fieri_phrases:
  - off the hook
  - like a game of blackjack at the Flavortown casino
  - bomb-dot-com tasty
  - dynamite
  - gangster
  - lights-out delicious
  - the real deal
  - bananas, and bananas is good
  - winner winner flavorful dinner